// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"
	"time"
)

type SpotifyToken struct {
	ID            int64     `json:"id"`
	SpotifyUserID string    `json:"spotifyUserID"`
	CreatedAt     time.Time `json:"createdAt"`
	RefreshToken  string    `json:"refreshToken"`
	AccessToken   string    `json:"accessToken"`
	ExpiresAt     time.Time `json:"expiresAt"`
	TokenType     string    `json:"tokenType"`
}

type User struct {
	ID          int64          `json:"id"`
	DisplayName string         `json:"displayName"`
	SpotifyID   string         `json:"spotifyID"`
	Country     sql.NullString `json:"country"`
	ImageUrl    sql.NullString `json:"imageUrl"`
}
