// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"database/sql"
	"time"
)

type Song struct {
	ID          int64          `json:"id"`
	SpotifyID   string         `json:"spotifyID"`
	Name        string         `json:"name"`
	Artist      []string       `json:"artist"`
	ReleaseDate string         `json:"releaseDate"`
	Image       sql.NullString `json:"image"`
	PreviewUrl  sql.NullString `json:"previewUrl"`
}

type SpotifyToken struct {
	ID            int64     `json:"id"`
	SpotifyUserID string    `json:"spotifyUserID"`
	CreatedAt     time.Time `json:"createdAt"`
	RefreshToken  string    `json:"refreshToken"`
	AccessToken   string    `json:"accessToken"`
	ExpiresAt     time.Time `json:"expiresAt"`
	TokenType     string    `json:"tokenType"`
}

type User struct {
	SpotifyID   string         `json:"spotifyID"`
	DisplayName string         `json:"displayName"`
	Country     sql.NullString `json:"country"`
	ImageUrl    sql.NullString `json:"imageUrl"`
	Choices     []string       `json:"choices"`
}

type UserPlaylist struct {
	ID            int32     `json:"id"`
	SpotifyUserID string    `json:"spotifyUserID"`
	Choice1       string    `json:"choice1"`
	Choice2       string    `json:"choice2"`
	Choice3       string    `json:"choice3"`
	Choice4       string    `json:"choice4"`
	Choice5       string    `json:"choice5"`
	Choice6       string    `json:"choice6"`
	Choice7       string    `json:"choice7"`
	Choice8       string    `json:"choice8"`
	Choice9       string    `json:"choice9"`
	Choice10      string    `json:"choice10"`
	CreatedAt     time.Time `json:"createdAt"`
	UpdatedAt     time.Time `json:"updatedAt"`
}
