// Code generated by sqlc. DO NOT EDIT.
// source: users.sql

package db

import (
	"context"
	"database/sql"
)

const createOrUpdateUser = `-- name: CreateOrUpdateUser :one
INSERT INTO users (
  display_name,
  spotify_id,
  country,
  image_url
) VALUES (
  $1,$2,$3,$4
) 
ON CONFLICT (spotify_id)
DO UPDATE 
SET display_name = $1,
    country = $3,
    image_url = $4
RETURNING id, display_name, spotify_id, country, image_url
`

type CreateOrUpdateUserParams struct {
	DisplayName string         `json:"displayName"`
	SpotifyID   string         `json:"spotifyID"`
	Country     sql.NullString `json:"country"`
	ImageUrl    sql.NullString `json:"imageUrl"`
}

func (q *Queries) CreateOrUpdateUser(ctx context.Context, arg CreateOrUpdateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createOrUpdateUser,
		arg.DisplayName,
		arg.SpotifyID,
		arg.Country,
		arg.ImageUrl,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.SpotifyID,
		&i.Country,
		&i.ImageUrl,
	)
	return i, err
}
