version: "3.9"
services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=plusxhub
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
